stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.prod.yml up --build -d
  only:
    - master # You can specify the branch you want to trigger the deployment on
