version: "3"
services:
  nestjs:
    build: ./weather-server
    ports:
      - "9001:9001"
    volumes:
      - ./weather-server:/app
    command: yarn start:dev

  weather-app:
    build: ./weather-app
    ports:
      - "9000:9000"
    volumes:
      - ./weather-app:/app
    command: yarn dev

  flask:
    build: ./weather-algo
    ports:
      - "9002:9002"
    environment:
      FLASK_ENV: development
    volumes:
      - ./weather-algo:/app
    command: python app.py

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
