version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weather-app:
    build: ./weather-app
    ports:
      - "9000:9000"
    volumes:
      - ./weather-app:/app
    command: dev

  nestjs:
    build: ./weather-server
    ports:
      - "9001:9001"
    volumes:
      - ./weather-server:/app
    command: start:dev
    depends_on:
      - postgres

  flask:
    build: ./weather-algo
    ports:
      - "9002:9002"
    environment:
      FLASK_ENV: development
    volumes:
      - ./weather-algo:/app
    depends_on:
      - postgres

volumes:
  postgres-data:
