version: "3"
services:
  nestjs:
    build: ./weather-server
    ports:
      - "9001:9001"
    volumes:
      - ./weather-server:/app
    command: start:dev

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "neko"
      POSTGRES_PASSWORD: "neko"
      POSTGRES_DB: "default_database"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weather-app:
    build: ./weather-app
    ports:
      - "9000:9000"
    volumes:
      - ./weather-app:/app
    command: dev

  flask:
    build: ./weather-algo
    ports:
      - "9002:9002"
    environment:
      FLASK_ENV: development
    volumes:
      - ./weather-algo:/app

volumes:
  postgres-data:
