version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "9011:9011"
    environment:
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_PORT: ${POSTGRES_DEV_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
