name: weather
version: 1.0.0
description: ""
main: index.js
scripts:
  # dev: concurrently "pnpm -F=weather-app dev" "pnpm -F=weather-server start:dev" "flask run --port 9002"
  dev: concurrently "pnpm -F=weather-app dev" "pnpm -F=weather-server start:dev" "cd weather-algo && source venv/bin/activate && flask run --port=9002"
keywords: []
author: ""
license: ISC
devDependencies:
  concurrently: ^7.6.0
  typescript: ^4.9.5
