name: weather
version: 1.0.0
description: ""
main: index.js
scripts:
  dev: concurrently "pnpm -F=weather-app dev" "pnpm -F=weather-server start:dev"
keywords: []
author: ""
license: ISC
devDependencies:
  concurrently: ^7.6.0
