name: weather-app
version: 0.1.0
private: true
scripts:
  dev: >-
    concurrently 'next dev -p 9000' 'yarn typed-scss-modules . -w
    --ignoreInitial -n 'none''
  build: next build
  start: next start
  lint: next lint
dependencies:
  '@ls-lint/ls-lint': ^1.11.2
  '@next/font': ^13.1.2
  '@reduxjs/toolkit': ^1.9.1
  '@types/node': 18.11.18
  '@types/react': 18.0.26
  '@types/react-dom': 18.0.10
  eslint: 8.31.0
  eslint-config-next: 13.1.1
  next: 13.1.1
  plotly.js: ^2.18.0
  react: 18.2.0
  react-dom: 18.2.0
  react-plotly.js: ^2.6.0
  react-redux: ^8.0.5
  sass: ^1.57.1
  sass-loader: ^13.2.0
  typescript: 4.9.4
  webpack: ^5.0.0
devDependencies:
  concurrently: ^7.6.0
  sass-alias: ^2.0.0
  typed-scss-modules: ^7.0.2
